apiVersion: v1
kind: Secret
metadata:
  name: strapi-db-user
  namespace: wopr
type: kubernetes.io/basic-auth
stringData:
  username: strapi
  password: <generate-something-secure>
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: strapi
  namespace: wopr
spec:
  cluster:
    name: wopr-config-db-cluster
  name: strapi
  owner: strapi