apiVersion: v2
name: woprcvat
version: 1.0.0
description: WOPR CVAT Application Chart
type: application

dependencies:
  - name: cvat
    version: "2.54.0"
    repository: "oci://registry-1.docker.io/cvat"