[theme]
base = "dark"
primaryColor = "#00ff00"
backgroundColor = "#000000"
secondaryBackgroundColor = "#111111"
textColor = "#00ff00"
#font = "Tilt Neon:https://fonts.googleapis.com/css2?family=Tilt+Neon&display=swap"
font = "Genos:https://fonts.googleapis.com/css2?family=Genos:ital,wght@0,100..900;1,100..900&display=swap"


[client]
toolbarMode = "viewer"

[server]
runOnSave = true
headless = true
showEmailPrompt = false

[browser]
gatherUsageStats = false
