apiVersion: v1
kind: Service
metadata:
  name: {{ include "wopr-config.fullname" . }}
  labels:
    {{- include "wopr-config.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "wopr-config.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
