---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wopr-config-db-cluster
  namespace: wopr
spec:
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQL:
        - configMapRefs:
          - name: {{ include "wopr-config.fullname" . }}-db-init
            key: schema.sql