services:
  wopr-cam:
    image: ghcr.io/travismontana/wopr/wopr-cam:latest
    user: "2222:2222"
    group_add:
      - 44  # video group
    ports:
      - "5000:5000"
    volumes:
      - /remote/wopr:/remote/wopr:rw
#      - /remote/config:/config:ro
    devices:
      - /dev/video0:/dev/video0
    environment:
      - OTEL_SERVICE_NAME=wopr-cam
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console,otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otel.monitoring.abode.tailandtraillabs.org
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - WOPR_CONFIG_SERVICE_URL=https://wopr-config.studio.abode.tailandtraillabs.org
      - STARTTRACE=/home/wopr/.local/bin/opentelemetry-instrument