services:
  openwebui:
    image: ghcr.io/travismontana/wopr/wopr-cam:latest
    ports:
      - "5000:5000"
    environment:
      - OTEL_SERVICE_NAME=wopr-cam
      - OTEL_TRACES_EXPORTER=console,otlp
      - OTEL_METRICS_EXPORTER=console,otlp
      - OTEL_EXPORTER_OTLP_ENDPOINT=https://otel.monitoring.abode.tailandtraillabs.org
      - OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
      - WOPR_CONFIG_SERVICE_URL=https://wopr-config.studio.abode.tailandtraillabs.org
