---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wopr-labelstudio-nfs-pvc
  namespace: wopr
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests
      storage: 1Ti
  storageClassName: ""
  volumeName: wopr-labelstudio-nfs-pv

