---
apiVersion: v1
stringData:
  username: wopr-config-db-user
  password: '<change to something S3c7e7!>'
kind: Secret
metadata:
  name: wopr-config-db-user-credentials
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth