---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wopr-db-cluster
spec:
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: wopr-api-initdb
            key: schema.sql
  managed:
    roles:
      - name: wopr-config-db-user
        comment: "wopr config database user"
        ensure: present
        login: true
        passwordSecret:
          name: wopr-config-db-user-credentials
        createdb: false
        createrole: false
      - name: wopr-db-user
        comment: "wopr database user"
        ensure: present
        login: true
        passwordSecret:
          name: wopr-db-user-credentials
        createdb: false
        createrole: false
      - name: wopr-cvat-db-user
        comment: "wopr cvat database user"
        ensure: present
        login: true
        passwordSecret:
          name: wopr-cvat-db-user-credentials
        createdb: false
        createrole: false
---
apiVersion: v1
stringData:
  username: wopr-config-db-user
  password: '<change to something S3c7e7!>'
kind: Secret
metadata:
  name: wopr-config-db-user-credentials
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  username: wopr-db-user
  password: '<change to something S3c7e7!>'
kind: Secret
metadata:
  name: wopr-db-user-credentials
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: v1
stringData:
  username: wopr-cvat-db-user
  password: '<change to something S3c7e7!>'
kind: Secret
metadata:
  name: wopr-cvat-db-user-credentials
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth