apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.nfs.pvName }}
spec:
  capacity:
    storage: {{ .Values.nfs.size }}
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  mountOptions:
{{- range .Values.nfs.mountOptions }}
    - {{ . }}
{{- end }}
  nfs:
    server: {{ .Values.nfs.server }}
    path: {{ .Values.nfs.path }}
