apiVersion: v1
kind: Service
metadata:
  name: {{ include "wpor-web.fullname" . }}
  labels:
    {{- include "wpor-web.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    protocol: TCP
    name: http
  selector:
    {{- include "wpor-web.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
