apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "strapi.fullname" . }}
  labels:
    {{- include "strapi.labels" . | nindent 4 }}
data:
  HOST: "0.0.0.0"
  PORT: "1337"
  NODE_ENV: {{ .Values.strapi.nodeEnv | quote }}
  
  # Database configuration
  DATABASE_CLIENT: "postgres"
  DATABASE_HOST: {{ .Values.postgresql.external.host | quote }}
  DATABASE_PORT: {{ .Values.postgresql.external.port | quote }}
  DATABASE_NAME: {{ .Values.postgresql.external.database | quote }}
  DATABASE_USERNAME: {{ .Values.postgresql.external.username | quote }}
  DATABASE_SSL: "false"
  DATABASE_SCHEMA: "public"
