apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcpsm
spec:
  provider:
    gcpsm:
      projectID: ttl-infra-auth
      auth:
        secretRef:
          secretAccessKeySecretRef:
            name: gcpsm-sa
            key: key.json
            namespace: external-secrets
