{{/*
WOPR - Wargaming Oversight & Position Recognition
Copyright (c) 2025 Bob Bomar <bob@bomar.us>
SPDX-License-Identifier: MIT
*/}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "wopr-api.fullname" . }}
  labels:
    {{- include "wopr-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ include "wopr-api.databaseUrl" . | quote }}
  jwt-secret-key: {{ .Values.secrets.JWT_SECRET_KEY | quote }}
