# Copyright 2026 Bob Bomar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

wopr-baseapp:
  app:
    name: wopr-directus
  replicaCount: 1

  image:
    registry: ghcr.io
    repository: directus/directus
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8055

  ingress:
    enabled: true
    hosts:
      - host: directus.wopr.tailandtraillabs.org
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: directus-tls
        hosts:
          - directus.wopr.tailandtraillabs.orgs
  pvc:
    - name: directus-uploads
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 10Gi
    - name: directus-extensions
      enabled: true
      accessModes:
        - ReadWriteOnce
      size: 5Gi
  volumes:
    - name: directus-uploads
      persistentVolumeClaim:
        claimName: directus-uploads
    - name: directus-extensions
      persistentVolumeClaim:
        claimName: directus-extensions
  volumeMounts:
    - name: directus-uploads
      mountPath: /directus/uploads
    - name: directus-extensions
      mountPath: /directus/extensions
  env:
    - name: DB_CLIENT
      value: pg
    - name: DB_HOST
      valueFrom:
        secretKeyRef:
          name: wopr-db-cluster-app
          key: host
    - name: DB_PORT
      valueFrom:
        secretKeyRef:
          name: wopr-db-cluster-app
          key: port
    - name: DB_DATABASE
      valueFrom:
        configMapKeyRef:
          name: wopr-config
          key: WOPR_METADATA_DB
    - name: DB_USER
      valueFrom:
        secretKeyRef:
          name: wopr-db-user-credentials
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: wopr-db-user-credentials
          key: password
    - name: SECRET
      valueFrom:
        secretKeyRef:
          name: wopr-db-user-credentials
          key: password
    - name: PUBLIC_URL
      value: https://directus.wopr.tailandtraillabs.org
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000