apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "thumbor.fullname" . }}-config
  labels:
    {{- include "thumbor.labels" . | nindent 4 }}
data:
  thumbor.conf: |
    {{- .Values.thumbor.config | nindent 4 }}