apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wopr-api.fullname" . }}-initdb
  labels:
    {{- include "wopr-api.labels" . | nindent 4 }}
data:
  schema.sql: |
{{ .Files.Get "files/schema.sql" | indent 4 }}
