apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "wopr-api.fullname" . }}-config
  labels:
    {{- include "wopr-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: config
data:
  # Service URLs
  {{- with .Values.config }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
  API_URL: {{ printf "%s/api/%s" .Values.config.services.apiServiceUrl .Values.config.services.apiVersion | quote }}