apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: labelstudio-secret
spec:
  refreshInterval: 1h0m0s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm
  target:
    name: labelstudio-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: labelstudio-pat
      remoteRef:
        key: labelstudio-pat
