---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wopr-config-db-cluster
spec:
  instances: 1
  storage:
    size: 1Gi
  enableSuperuserAccess: true
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: wopr-api-initdb
            key: schema.sql
  managed:
    roles:
      - name: wopr-db-user
        ensure: present
        passwordSecret:
          name: wopr-db-user-credentials
        createdb: true