imgproxy:
  resources:
    ingress:
      enabled: true
      className: wopr-traefik
      hosts:
        - imgproxy.wopr.tailandtraillabs.org
      tls:
        - secretName: wildcard-tls
          hosts:
            - imgproxy.wopr.tailandtraillabs.org