
apiVersion: v2
name: directus-stack
description: Directus headless CMS
type: application
version: 1.0.0
appVersion: "11.13.0"


dependencies:
  - name: directus
    repository: https://directus-labs.github.io/helm-chart/
    version: 2.0.7