apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "thumbor.fullname" . }}
  labels:
    {{- include "thumbor.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "thumbor.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "thumbor.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
      containers:
      - name: thumbor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.thumbor.port }}
          protocol: TCP
        env:
        - name: HEALTHCHECK_ROUTE
          value: "/"
        - name: THUMBOR_PORT
          value: {{ .Values.thumbor.port | quote }}
        - name: THUMBOR_NUM_PROCESSES
          value: {{ .Values.thumbor.numProcesses | quote }}
        - name: MAX_AGE
          value: {{ .Values.thumbor.maxAge | quote }}
        - name: MAX_AGE_TEMP_IMAGE
          value: {{ .Values.thumbor.maxAgeTempImage | quote }}
        - name: RESULT_STORAGE_EXPIRATION_SECONDS
          value: {{ .Values.thumbor.resultStorageExpiration | quote }}
        - name: ALLOW_UNSAFE_URL
          value: {{ .Values.thumbor.allowUnsafeUrl | quote }}
        - name: AUTO_WEBP
          value: {{ .Values.thumbor.autoWebp | quote }}
        volumeMounts:
        - name: nfs-images
          mountPath: {{ .Values.nfs.mountPath }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: nfs-images
        nfs:
          server: {{ .Values.nfs.server }}
          path: {{ .Values.nfs.path }}
      restartPolicy: Always