label-studio:
  global: 
    pgConfig:
      host: "wopr-db-cluster-rw.wopr.svc.cluster.local"
      port: 5432
      dbName: "wopr-labelstudio-db-database"
      userName: "wopr-labelstudio-db-user"
      password:
        secretName: "wopr-labelstudio-db-user-credentials"
        secretKey: "password"
    persistence:
      enabled: true
      config:
        volume:
          storageClass: "rook-cephfs"
          size: 10Gi
          existingClaim: "wopr-labelstudio-pvc"
    extraEnvironmentVars:
      LOCAL_FILES_SERVING_ENABLED: "true"
      LOCAL_FILES_DOCUMENT_ROOT: "/export/wopr/labelstudio/data"
  app:
    ingress:
      enabled: true
      className: "wopr-traefik"
      host: "labelstudio.wopr.tailandtraillabs.org"
      tls:
        - secretName: "wildcard-tls"
          hosts:
            - "labelstudio.wopr.tailandtraillabs.org"
    extraVolumes:
    - name: wopr-storage
      persistentVolumeClaim:
        claimName: wopr-labelstudio-nfs-pvc
    extraVolumeMounts:
    - name: wopr-storage
      mountPath: /label-studio/mydata
  postgresql:
    enabled: false
  redis:
    enabled: true