# Copyright 2026 Bob Bomar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

label-studio:
  global: 
    pgConfig:
      host: "wopr-db-cluster-rw.wopr.svc.cluster.local"
      port: 5432
      dbName: "wopr-labelstudio-db-database"
      userName: "wopr-labelstudio-db-user"
      password:
        secretName: "wopr-labelstudio-db-user-credentials"
        secretKey: "password"
    persistence:
      enabled: true
      config:
        volume:
          storageClass: "rook-cephfs"
          size: 10Gi
          existingClaim: "wopr-labelstudio-pvc"
    extraEnvironmentVars:
      LOCAL_FILES_SERVING_ENABLED: "true"
      LOCAL_FILES_DOCUMENT_ROOT: "/label-studio/mydata"
  app:
    ingress:
      enabled: true
      className: "wopr-traefik"
      host: "labelstudio.wopr.tailandtraillabs.org"
      tls:
        - secretName: "wildcard-tls"
          hosts:
            - "labelstudio.wopr.tailandtraillabs.org"
    extraVolumes:
    - name: wopr-storage
      persistentVolumeClaim:
        claimName: wopr-labelstudio-nfs-pvc
    extraVolumeMounts:
    - name: wopr-storage
      mountPath: /label-studio/mydata
  postgresql:
    enabled: false
  redis:
    enabled: true