# Copyright 2026 Bob Bomar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

open-webui:
  ollama:
    enabled: false
  persistence:
    storageClass: "rook-ceph-block"
  sso:
    enabled: true
    google:
      enabled: true
      enableSignup: true
      mergeAccountsByEmail: true
      clientId: "522570646134-4nmsbnlql25k4l1f6u96qa7mqlvu3bne.apps.googleusercontent.com"
      clientExistingSecret: "openwebui-google-oauth"
      clientExistingSecretKey: "clientSecret"
  ollamaUrls:
    - "http://groth.abode.tailandtraillabs.org:11434"
  ollamaUrlsFromExtraEnv: true
  tika:
    enabled: true
  ingress:
    enabled: true
    class: "wopr-traefik"
    host: "openwebui.wopr.tailandtraillabs.org"
    tls: true
    existingSecret: "wildcard-tls"
