open-webui:
  ollama:
    enabled: false
  persistence:
    storageClass: "rook-ceph-block"
  #sso:
  #  enabled: true
  #  google:
  #    enabled: true
  #    enableSignup: true
  #    mergeAccountsByEmail: true
  #    clientId: "522570646134-4nmsbnlql25k4l1f6u96qa7mqlvu3bne.apps.googleusercontent.com"
  #    clientExistingSecret: "openwebui-google-oauth"
  #    clientExistingSecretKey: "clientSecret"
  ollamaUrls:
    - "http://groth.abode.tailandtraillabs.org:11434"
  ollamaUrlsFromExtraEnv: true
  tika:
    enabled: true
  ingress:
    enabled: true
    class: "wopr-traefik"
    host: "openwebui.wopr.tailandtraillabs.org"
    tls: true
    existingSecret: "wildcard-tls"
