---
apiVersion: ceph.rook.io/v1
kind: CephObjectStore
metadata:
  name: objectstore
  namespace: rook-ceph
spec:
  metadataPool:
    replicated:
      size: 1
  dataPool:
    replicated:
      size: 1
  gateway:
    port: 80
    instances: 1
---
apiVersion: ceph.rook.io/v1
kind: CephObjectStoreUser
metadata:
  name: wopr-s3-user
  namespace: rook-ceph
spec:
  store: objectstore
  displayName: "WOPR S3 User"
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: wopr-s3-bucket-claim
  namespace: rook-ceph
spec:
  bucketName: wopr-s3-bucket
  storageClassName: rook-ceph-bucket-wopr
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: rook-ceph-bucket-wopr
provisioner: rook-ceph.ceph.rook.io/bucket
parameters:
  objectStoreName: woppr-store
  objectStoreNamespace: wopr
  bucketName: wopr-s3-bucket
reclaimPolicy: Delete