wopr-baseapp:
  app:
    name: wopr-filebrowser
  replicaCount: 1

  image:
    registry: docker.io
    repository: filebrowser/filebrowser
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 8080

  ingress:
    enabled: true
    className: wopr-traefik
    hosts:
      - host: filebrowser.wopr.tailandtraillabs.org
        paths:
          - path: /
            pathType: Prefix
    tls: 
      - secretName: wopr-filebrowser-tls
        hosts:
          - filebrowser.wopr.tailandtraillabs.org

  env:
    - name: WOPR_API_URL
      valueFrom:
        configMapKeyRef:
          name: wopr-config
          key: WOPR_API_URL
  
  
  volumeMounts:
    - name: wopr-data
      mountPath: /srv
      readOnly: true
    - name: wopr-filebrowser-database-pvc
      mountPath: /database
    - name: wopr-filebrowser-config-pvc
      mountPath: /config

  volumes:
    - name: wopr-data
      persistentVolumeClaim:
        claimName: wopr-nfs-pvc
    - name: wopr-filebrowser-database-volume
      persistentVolumeClaim:
        claimName: fb-db-pvc
    - name: wopr-filebrowser-config-volume
      persistentVolumeClaim:
        claimName: fb-config-pvc

  pvc:
    - name: fb-db-pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi
      storageClassName: rook-ceph-block
    - name: fb-config-pvc
      enabled: true
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
      storageClassName: rook-ceph-block