apiVersion: v2
name: wopr-cnpg
description: CloudNative PostgreSQL application stack
type: application
version: 1.0.0
appVersion: "8.5.4"


dependencies:
  - name: cloudnative-pg
    repository: https://cloudnative-pg.github.io/charts/
    version: 0.27.0
