apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wopr-baseapp.fullname" . }}
  labels:
    {{- include "wopr-baseapp.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wopr-baseapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- if .Values.podAnnotations }}
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      {{- end }}
      labels:
        {{- include "wopr-baseapp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: {{ include "wopr-baseapp.fullname" . }}
        image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.command }}
        command: {{ .Values.command }}
        {{- end }}
        {{- if .Values.args }}
        args:
          {{- toYaml .Values.args | nindent 8 }}
        {{- end }}
        {{- if .Values.service }}
        ports:
        - name: {{ include "wopr-baseapp.fullname" . }}
          containerPort: {{ .Values.service.port }}
          protocol: {{ include "wopr-baseapp.serviceProtocol" . }}
        {{- end }}
        env:
          - name: OTEL_SERVICE_NAME
            value: {{ include "wopr-baseapp.fullname" . }}
        {{- if .Values.env }}
          {{- toYaml .Values.env | nindent 10 }}
        {{- end }}
        {{- if .Values.volumeMounts}}
        volumeMounts:
          {{- toYaml .Values.volumeMounts | nindent 10 }}
        {{- end }}
        {{- if .Values.service.port}}
        {{- if ne .Values.livenessProbe.enabled false }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        {{- end}}
        {{- if ne .Values.readinessProbe.enabled false }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.port }}
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        {{- end}}
        {{- end}}
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
      {{- with .Values.sidecarContainers }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      {{- if .Values.volumes}}
      volumes:
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
