# Copyright 2026 Bob Bomar
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.pv }}
{{- range .Values.pv }}
{{- if .enabled }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .name }}
  labels:
    {{- include "wopr-baseapp.labels" $ | nindent 4 }}
    {{- if .extraLabels }}
    {{- toYaml .extraLabels | nindent 4 }}
    {{- end }}
spec:
  capacity:
    storage: {{ .size }}
  accessModes:
  {{- toYaml .accessModes | nindent 2 }}
  persistentVolumeReclaimPolicy: {{ .reclaimPolicy | default "Retain" }}
  {{- if .storageClass }}
  storageClassName: {{ .storageClass | quote }}
  {{- end }}
  {{- if .mountOptions }}
  mountOptions:
  {{- toYaml .mountOptions | nindent 2 }}
  {{- end }}
  {{- if .nfs }}
  nfs:
    server: {{ .nfs.server }}
    path: {{ .nfs.path }}
  {{- end }}
  {{- if .hostPath }}
  hostPath:
    path: {{ .hostPath.path }}
    {{- if .hostPath.type }}
    type: {{ .hostPath.type }}
    {{- end }}
  {{- end }}
  {{- if .csi }}
  csi:
    {{- toYaml .csi | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}