apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: wopr-config-db-database
  namespace: wopr
spec:
  name: wopr-config-db-database
  owner: wopr-config-db-database-owner
  cluster:
    name: wopr-config-db-cluster
